name: Deploy to EC2 using AWS CLI

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      #- name: Install AWS CLI
        #run: |
          #sudo apt-get update
          #sudo apt-get install -y awscli

      - name: Deploy to EC2 via SSM
        run: |
          aws ssm send-command \
            --instance-ids "i-034d8cc8050ca7632" \
            --document-name "AWS-RunShellScript" \
            --comment "GitHub Actions EC2 deployment" \
            --parameters commands='cd /var/www/html && git pull origin main && sudo systemctl restart httpd' \
            --output text
